# Generated by Django 3.1.7 on 2021-03-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tfno', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('foto', models.ImageField(upload_to='administrador', verbose_name='Foto')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='categoria', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tfno', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('foto', models.ImageField(upload_to='mensajeros', verbose_name='foto')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total_valor_vendido', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Venta total del dia')),
                ('ventas_por_categoria', models.CharField(max_length=500, verbose_name='Ventas por Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('tfno', models.IntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('logo', models.ImageField(upload_to='restaurantes', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tfno', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('foto', models.ImageField(upload_to='usuarios', verbose_name='Foto')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('valoracion', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='valoracion')),
                ('comentario', models.CharField(max_length=2000, verbose_name='Reseñas')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.restaurante', verbose_name='Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total_vendido', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Venta total del dia')),
                ('top_ventas_por_restaurantes', models.CharField(max_length=500, verbose_name='Top de Restaurantes por venta')),
                ('categoria_mas_vendida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deliveryfood.categoria', verbose_name='Categoria mas vendida')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Nombre')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo aproximado de preparacion (min)')),
                ('foto', models.ImageField(upload_to='productos', verbose_name='Foto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.categoria', verbose_name='Categoria')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.restaurante', verbose_name='Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('hora_solicitud', models.TimeField(verbose_name='Hora de solicitud')),
                ('hora_entrega', models.TimeField(verbose_name='Hora de entrega')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo aproximado del pedido (min)')),
                ('estado', models.CharField(choices=[('E', 'En Proceso'), ('M', 'Enviando'), ('C', 'Cancelado'), ('F', 'Facturado')], default='E', max_length=20, verbose_name='Estado')),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deliveryfood.mensajero', verbose_name='Mensajero')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deliveryfood.restaurante', verbose_name='Restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryfood.restaurante', verbose_name='Restaurante'),
        ),
    ]
